import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next.js my learning",
    template: "%s | learn this shit",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "20px" }}>
          Header
        </header>
        {children}
        <footer style={{ backgroundColor: "lightgrey", padding: "20px" }}>
          Footer
        </footer>
      </body>
    </html>
  );
}
